export default [
  {
    projectName: "Weigh Me",
    id: "weigh-me",
    units: "Kg",
    text: "A graph to track my weight",
    xAxis: ["Day 1", "Day 2", "Day 3"],
    projectData: [
      { label: "Paul",
        id: "1",
        borderColor: "red",
        data: [76, 77, 75],
        fill: true,
      },
    ] 
  },
  {
    projectName: "Weigh us",
    id: "weigh-us",
    units: "Kg",
    text: "A graph to track our group weight",
    xAxis: ["Day 1", "Day 2", "Day 3"],
    projectData: [
      { label: "Paul",
        id: "1",
        borderColor: "red",
        data: [76, 77, 75],
        fill: true,
      },
      { label: "Jon",
        id: "2",
        borderColor: "blue",
        data: [90, 85, 75],
        fill: true,
      },
      { label: "Jeffefe",
        id: "3",
        borderColor: "Green",
        data: [60, 60, 62],
        fill: true,
      },
    ]     
  }, {
  projectName: "Electricity Usage",
  id: "electricity-usage",
  units: "KWH",
  text: "A graph to track my electricity usage",
  xAxis: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"],
  projectData: [
    { label: "January",
      id: "1",
      borderColor: "red",
      data: [960, 950, 930, 930, 920],
      fill: true,
    },
    { label: "Febuary",
      id: "2",
      borderColor: "blue",
      data: [800, 700, 650, 500, 650],
      fill: true,
    },
    { label: "March",
      id: "3",
      borderColor: "Green",
      data: [600, 580, 950, 750, 600],
      fill: true,
    },
  ] 
  }
];